######################################################################
# Automatically generated by qmake (3.0) ??????? ????? ????? 28 13:33:53 2019
######################################################################

TEMPLATE = app
TARGET = SampleProjects
INCLUDEPATH += .
QT += gui widgets 
# Input
SOURCES += testmain.cpp
